Added protobuf bom to gradle libs. Libraries upgrade
micronaut-projects/micronaut-grpc pull request #596
Opened 2022-10-14 10:29 UTC by altro3

2022-10-16 12:03 UTC, graemerocher requested changes

2022-10-16 12:03 UTC, graemerocher commented on gradle.properties
> +githubCoreBranch=3.7.x
needs to target 4.0.x

2022-10-16 12:03 UTC, graemerocher commented on gradle.properties
>  projectVersion=3.4.0-SNAPSHOT
bump project version to 4.0.0-SNAPSHOT

2022-10-16 14:13 UTC, altro3 commented on gradle.properties
>  projectVersion=3.4.0-SNAPSHOT
@graemerocher fixed

2022-10-16 14:13 UTC, altro3 commented on gradle.properties
> +githubCoreBranch=3.7.x
@graemerocher fixed

2022-10-22 15:37 UTC, wetted commented
This should target the `micronaut-grpc` `4.0.x` branch, which is what we merge to master when to point it to `githubCoreBranch 4.0.x` for https://github.com/micronaut-projects/micronaut-core/issues/8059. I've made that change. I'll also add my review when I'm back early next week. I think it needs some other changes. Thank you for your contribution.

2022-10-25 13:50 UTC, graemerocher commented
@altro3 could you resolve the conflicts?

2022-10-25 13:59 UTC, graemerocher commented
Hmm, guess I will have to use the command line to merge, since the Github UI says it is unmergeable

2022-10-25 14:01 UTC, altro3 commented
@altro3 maybe need to try create new merge request?

2022-10-25 14:02 UTC, altro3 commented
@graemerocher maybe need to try create new merge request?

2022-10-25 14:05 UTC, altro3 commented
see this: https://github.com/micronaut-projects/micronaut-grpc/pull/596

2022-10-25 14:28 UTC, wetted requested changes

2022-10-25 14:28 UTC, wetted commented on gradle/libs.versions.toml
remove all the `micronaut-*` items here and use the `mn` catalog in dependency closures instead

2022-10-25 14:28 UTC, wetted commented on gradle/libs.versions.toml
> +javax-annotation-api = { module = 'javax.annotation:javax.annotation-api' }
remove this catalog item and dependencies on `javax.annotation`. We are migrating code to use `jakarta.annotation` which mostly affects `@PostCreate` and `@PreDestroy` annotations.

2022-10-25 14:28 UTC, wetted commented on gradle/libs.versions.toml
>  graal = { module = "org.graalvm.nativeimage:svm" }
remove this and use `mn.graal` in dependency closures for build scripts. Ditto for logback (use `mn.logback`) and projectreactor (`mn.reactor`)

2022-10-25 14:28 UTC, wetted commented on grpc-client-runtime/build.gradle
> +    testCompileOnly libs.javax.annotation.api
remove and fix code to use `jakarta.annotation` instead.

2022-10-25 14:28 UTC, wetted commented on grpc-client-runtime/build.gradle
>      implementation libs.micronaut.buffer.netty
Change all these `micronaut` dependencies to use the `mn` catalog, `mn.micronaut.runtime`, etc.

2022-10-25 14:28 UTC, wetted commented on grpc-client-runtime/build.gradle
>          enabled = true
these are defaults and not necessary

2022-10-25 14:28 UTC, wetted commented on grpc-health/build.gradle
>      api libs.micronaut.runtime
Change all `micronaut` dependencies to use the `mn` catalog, `mn.micronaut.runtime`, etc.

2022-10-25 14:28 UTC, wetted commented on grpc-opentracing/build.gradle
>      api libs.micronaut.runtime
Change all these `micronaut` dependencies to use the `mn` catalog, `mn.micronaut.runtime`, etc.

2022-10-25 14:28 UTC, wetted commented on grpc-opentracing/build.gradle
> +    testCompileOnly libs.javax.annotation.api
remove and use `jakarta.annotation` instead

2022-10-25 14:28 UTC, wetted commented on grpc-server-runtime/build.gradle
> +    implementation libs.micronaut.buffer.netty
use `mn` catalog instead

2022-10-25 14:28 UTC, wetted commented on grpc-server-runtime/build.gradle
> +    testCompileOnly libs.javax.annotation.api
remove, use jakarta annotation in code

2022-10-25 14:28 UTC, wetted commented on grpc-server-runtime/build.gradle
>          enabled = true
these are defaults and not needed

2022-10-25 14:28 UTC, wetted commented on settings.gradle
> +enableFeaturePreview 'TYPESAFE_PROJECT_ACCESSORS'
Change all the build.gradle files to use this feature; e.g. instead of `api project(":grpc-annotation")` use `api projects.grpcAnnotation`

2022-10-25 14:28 UTC, wetted commented on settings.gradle
> +    }
This is no longer idiomatic for Micronaut module builds. Remove `dependencyResolutionManagement.versionCatalogs` and use the build plugin instead. See https://github.com/micronaut-projects/micronaut-project-template/blob/09c49b0c2fcc7692c6eda6b79f24775a41ff1595/settings.gradle#L17

```
micronautBuild {
    importMicronautCatalog()
}
```

2022-10-25 14:28 UTC, wetted commented on test-suite-groovy/build.gradle
> +    compileOnly "javax.annotation:javax.annotation-api"
remove and change code to use `jakarta.annotation`

2022-10-25 14:52 UTC, wetted commented on gradle/libs.versions.toml
> +javax-annotation-api = { module = 'javax.annotation:javax.annotation-api' }
Fair enough, OK.  The dependency is exposed by the micronaut catalog, so use that instead of making one in `libs`

`mn.javax.annotation.api`

2022-11-03 11:21 UTC, closed without merging